gui:
  theme:
    activeBorderColor:
      - "#FF9E64" # Neon orange for active elements
      - bold
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    inactiveBorderColor:
      - "#4db0c9" # Balanced cyan-blue for inactive elements
    optionsTextColor:
      - "#4db0c9" # Matching inactive border color
    selectedLineBgColor:
      - "#4877ab" # Balanced blue for selected lines
    cherryPickedCommitBgColor:
      - "#3D99FF" # Matching selected line color
    cherryPickedCommitFgColor:
      - "#FFFFFF" # White text for contrast
    unstagedChangesColor:
      - "#FF9E64" # Neon orange for unstaged changes
    defaultFgColor:
      - "#c8d3f5"
  scrollHeight: 4

  nerdFontsVersion: "3"
  border: "rounded"
  # showCommandLog: true
  # showBottomLine: true
  # showFileTree: true
  # showRandomTip: true
  # showIcons: true

# Custom commands section - Define what the keybindings actually do
customCommands:
  - key: "<c-g>"
    command: "echo {{ .Repo.FileDir() }}/{{ .SelectedFile.Name }} | tr -d '\\n' | pbcopy"
    # ^ Copies the full file path to clipboard without newline
    # Use 'xclip -selection clipboard' or 'xsel -b' instead of pbcopy on Linux
    context: "files" # Only active in the file view
    description: "Edit in Neovim current running instance" # Appears in Lazygit's keybinding help
    subprocess: true # Run as a subprocess
    loadingText: "Preparing file for Neovim..." # Shown while command runs

git:
  paging:
    colorArg: always
    pager: delta
#     useConfig: true
# os:
#   editCommand: "nvim"
#   editCommandTemplate: '{{editor}} --server \\\\.\\pipe\\nvim-server --remote-tab "{{filename}}"'
