@echo off
echo Closing Stream Deck...
taskkill /f /im "StreamDeck.exe"
echo Waiting 3 seconds...
timeout /t 3 /nobreak
echo Starting Stream Deck...
start "" "C:\Program Files\StreamDeck\StreamDeck.exe"
echo Done!
